name: End to end test

permissions:
  id-token: write
  pages: write
  contents: read

on:
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  cypress-e2e:
    name: Run Cypress E2E tests
    runs-on: ubuntu-latest
    container: cypress/browsers:node-20.11.0-chrome-121.0.6167.85-1-ff-120.0-edge-121.0.2277.83-1

    steps:
      - uses: actions/checkout@v4
      - name: Cypress install
        run: npm ci --legacy-peer-deps
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install: false
          browser: chrome
      - name: Generate multi report
        run: npm run cucumber:multi-report
      - name: Setup pages
        uses: actions/configure-pages@v3
      - name: Create report artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: cypress/e2e/reports/html
  
   deploy-reports:

     environment:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
     needs: cypress-e2e
     runs-on: ubuntu-latest
     steps:
       - name: Deploy report to GitHub Pages
         id: deployment
         uses: actions/deploy-pages@v4


